[build]
  command = "npm run build"
  publish = ".next"

[secrets_scanning]
  # Leave scanner ON but tell it to ignore these safe public keys
  omit_keys = [
    "NEXT_PUBLIC_SUPABASE_ANON_KEY",
    "NEXT_PUBLIC_SUPABASE_URL"
  ]
